services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mdb'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=gp'
    ports:
      - 5432:5432
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379