CREATE TABLE EMAIL_DATA
(
    ID      BIGINT GENERATED ALWAYS AS IDENTITY,
    UUID    UUID   NOT NULL,
    USER_ID BIGINT NOT NULL,
    EMAIL   VARCHAR(200),

    CONSTRAINT EMAIL_DATA_PK PRIMARY KEY (ID),
    CONSTRAINT EMAIL_DATA_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT EMAIL_DATA_UNIQUE UNIQUE (EMAIL)
);