CREATE TABLE PHONE_DATA
(
    ID      BIGINT GENERATED ALWAYS AS IDENTITY,
    UUID    UUID   NOT NULL,
    USER_ID BIGINT NOT NULL,
    PHONE   VARCHAR(13),

    CONSTRAINT PHONE_DATA_PK PRIMARY KEY (ID),
    CONSTRAINT PHONE_DATA_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT PHONE_DATA_UNIQUE UNIQUE (PHONE)
);