CREATE TABLE USERS
(
    ID            BIGINT GENERATED ALWAYS AS IDENTITY,
    UUID          UUID NOT NULL,
    NAME          VARCHAR(500),
    PASSWORD      VARCHAR(60),
    DATE_OF_BIRTH DATE,

    CONSTRAINT USERS_PK PRIMARY KEY (ID)
);

