CREATE TABLE ACCOUNT
(
    ID              BIGINT GENERATED ALWAYS AS IDENTITY,
    UUID            UUID   NOT NULL,
    USER_ID         BIGINT NOT NULL,
    BALANCE         DECIMAL,
    INITIAL_BALANCE DECIMAL,

    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID),
    CONSTRAINT ACCOUNT_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);